/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_wjdiankong_encryptdemo_MainActivity */

#ifndef _Included_cn_wjdiankong_encryptdemo_MainActivity
#define _Included_cn_wjdiankong_encryptdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_wjdiankong_encryptdemo_MainActivity
 * Method:    isEquals
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_wjdiankong_encryptdemo_MainActivity_isEquals
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
